networks:
  inception-net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oualid/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oualid/data/wordpress

secrets:
  db_passwd:
    file: ../secrets/db_password.txt
  db_root_passwd:
    file: ../secrets/db_root_password.txt
  wp_credentials:
    file: ../secrets/wp_credentials.txt
  ftp_credentials:
    file: ../secrets/ftp_credentials.txt

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception-net
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_passwd
      - db_root_passwd
    restart: on-failure

  redis:
    container_name: redis
    build:  ./requirements/bonus/redis
    env_file:
      - .env
    networks:
      - inception-net
    restart: on-failure
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    networks:
      - inception-net
    secrets:
      - ftp_credentials
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "6000-6010:6000-6010"
    depends_on:
      - wordpress
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inception-net
    depends_on:
      - mariadb
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception-net
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - wp_credentials
    depends_on:
      - mariadb
      - redis
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception-net
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - adminer
    restart: on-failure
    